### ISSUE TITLE
How download tagged file?

### ISSUE THREAD

**Issue by onbatt** [fpiraneo/oclife#22]
Thank you for your application, but I have not found the way to download the file. Only previews.
It is very useful. at least a link to the "Files" app

**Comment by valessiobrito** [comment]
:+1:  Thanks for the work. When you want to provide link to display other types of documents or download?

**Comment by onbatt** [comment]
23.04.2015 17:54, Valessio Soares de Brito пишет:
>
> :+1: Thanks for the work. When you want to provide link to display 
> other types of documents or download?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/fpiraneo/oclife/issues/22#issuecomment-95612074>.
>
Sorry, English is not a native language for me :)
Unfortunately I do not know how to do it in owncloud (I'm not very 
familiar with PHP)
I use your module for sorting a large number of photographs. After I 
chose the tag I see small previews of images. But I do not know how now 
download the full size image. Can you add a button to download for preview?
Thanks for your work.

B.R.
Batchenko Aleksandr

-- 
С Уважением Батченко Александр

**Comment by fpiraneo** [comment]
Gentleman, thank you very much for your appreciation. Lot of persons ask me to introduce functions to allows download / viewing of several kind of documents directly from the "tag" view. This was not the functionality I thought from the beginning because normally it should be done by the "file" application of owncloud. I tried also to ask owncloud people for a deeper tag support on their file but they are not interested in tagging. Actually I don't have the time to develop more functionalities on oclife, I'm very sorry for that. I try to send my application for owncloud team and try to get from them a regular job... :-D In such case I can introduce all the functionalities peoples need.

**Comment by valessiobrito** [comment]
@onbatt see my "pog":  https://github.com/valessiobrito/oclife/commit/cdb2b172f1f4e24ae7388aecff49a598798d2406 

Is code enable download files on click in label.
