### ISSUE TITLE
plugin doesn't work with shared photos

### ISSUE THREAD

**Issue by hutchic** [fpiraneo/oclife#5]
Steps to reproduce:
- login as user A
- tag a photo
- share the photo with user B
- login as user B
- view the tag

**Actual Result**
Photo displays as "No image available"

**Expected Result**
If the user has permission to view the photo it should be displayed

**Comment by datenfalke** [comment]
Hello!

I realized that tags (shared to "all") only work for shared files - not for files inside of shared folders. Is this correct?

I would like to have a shared folder (for a group of users) including subfolders which are full of pictures. These pictures should be tagged and filtered by tag by each user of the group.

If user A shares a folder with a group, the included files are not shown if user B (in the group) chooses a tag. You will get an empty result - also if user B chooses the "root" tag.

If a folder is shared to a user (not a group) you will get "image not available" instead of nothing - but still not what is needed.

Only if I share a picture (or multiple which can only done one by one) with a user, this picture shows up when choosing a tag.

Is it possible to code the functionality for group shared folders regarding oclife tags? If you think it is not so complicated I would try by myself, because I need the functionality for a customer. 

Thank you and happy New Year!
